import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import SidebarContextProvider from "./Context/SidebarContext";
import "./globals.css";

const open_sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Do Your Own Will",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        <SidebarContextProvider>{children}</SidebarContextProvider>
      </body>
    </html>
  );
}
